### ISSUE TITLE
Some people are unable to log in to the app

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#101]
So far I learned that Ignacio and Michał K are unable to log in to the app. After clicking the Google login button... nothing happens. Any way we could look into this? @Tade0 @theanxy @karolsojko Thanks!

**Comment by theanxy** [comment]
Awaiting @mkawalec to provide more information

**Comment by theanxy** [comment]
According to @mkawalec, he couldn't reproduce that anymore. Must have been fixed by #102. Let's reopen if the problem persists.
