### ISSUE TITLE
Fix bot's name

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#108]
Can we please set the name of the bot that is sending reminders about deadlines, as well as comments notifications to "Unleash" and use appropriate icon?

So, instead: https://www.dropbox.com/s/3f21x3rs6m0b7dj/Screenshot%202016-02-24%2012.55.41.png?dl=0

Have this: https://www.dropbox.com/s/klofyntxi6s48mk/Screenshot%202016-02-24%2012.57.20.png?dl=0

Thanks!

**Comment by theanxy** [comment]
@Tade0 (Make sure to work with https://github.com/x-team/unleash-slack-bot and not the original repo, thanks! :relaxed: )

**Comment by karolsojko** [comment]
@jkbdbrnwsk can you test it on staging ?

**Comment by jkbdbrnwsk** [comment]
Do we have a separate bot for staging? Wouldn't want to post some dummy data to official channels.

**Comment by karolsojko** [comment]
@jkbdbrnwsk : yes, staging has a different staging bot

**Comment by jkbdbrnwsk** [comment]
Kewl, thanks. Furious testing incoming.
