### ISSUE TITLE
Slackbot comment notifications are not working

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#109]
Looks like the bot is successfully posting #unleash notifications, due date notifications, but it's *not posting* Slack notifications about new card comments (e-mail notifications are working, though). Please take a look. :)

**Comment by jkbdbrnwsk** [comment]
Can you guys please take a look if we actually have such feature in the code? Or did we only implement e-mail notifications?

**Comment by karolsojko** [comment]
Yup, confirming this is implemented but not working: https://github.com/x-team/unleash/blob/develop/app/scripts/services/comments.js#L89

**Comment by jkbdbrnwsk** [comment]
Thanks.

**Comment by jkbdbrnwsk** [comment]
@theanxy @Tade0 Gents, could one of you take a look at this? Please feel free to reach out if you need more details / if the ticket description is too vague. ;)

**Comment by theanxy** [comment]
Fixed in https://github.com/x-team/unleash-slack-bot/commit/e8ad7d45920fd210a84fd190d1cbffff5c29f047, deploying to `staging`

**Comment by theanxy** [comment]
Also fixed wording a bit in 1e81846.

@jkbdbrnwsk This is how it’s supposed to work at the moment (you can test it on `staging`): 
![screen shot 2016-03-02 at 19 01 22](https://cloud.githubusercontent.com/assets/92843/13469823/3eadf8e0-e0a9-11e5-9a37-c114cd914548.png)

Please let me know in case copy or styling changes are needed. I can freely adjust it to your needs.

**Comment by jkbdbrnwsk** [comment]
It works just fine, thanks a bunch! I would just remove the greeting: "Hello, %name%!"
