### ISSUE TITLE
Due date calendar not showing up in the admin panel

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#111]
As the title says, clicking the input doesn't trigger the calendar: https://www.dropbox.com/s/t0tyegtn9df4pzn/Screenshot%202016-02-24%2017.07.08.png?dl=0

**Comment by theanxy** [comment]
@jkbdbrnwsk to verify on `staging` :sparkles:

**Comment by jkbdbrnwsk** [comment]
Works like a charm, thanks!
