### ISSUE TITLE
Change due date notifications channel

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#114]
Please change the channel that due date notifications are going to - to: #unleash-notifications

https://www.dropbox.com/s/y78b1cbo1tpgeaw/Screenshot%202016-02-29%2013.56.03.png?dl=0

**Comment by theanxy** [comment]
Updated channel settings in Travis. @karolsojko Can we trigger rebuilding the bot in Tutum without a new commit?

**Comment by karolsojko** [comment]
Yeah, you just have to rebuild the ones. I've triggered the builds - should be fixed when they deploy
