### ISSUE TITLE
Mark notifications as sent

### ISSUE THREAD

**Issue by karolsojko** [x-team/unleash#115]
When the app gets redeployed or the container restarts - pending notifications are sent once again. So when the container was starting over and over again (it was failing due to lack of memory) then the app notified people each and every time about the same thing.

Solution: once the notification is sent it should be marked as sent and not be send once again

**Comment by jkbdbrnwsk** [comment]
Would be great if anyone could pick this up relatively soon, it's pretty confusing for the devs to receive notifications about goals that have been already completed. Cheers, gents!

**Comment by jkbdbrnwsk** [comment]
Shall we close this one yet, Karol? :)

**Comment by karolsojko** [comment]
no, every time the app redeploys or new version is deployed the notifications are sent again - even the ones that were already sent

**Comment by jkbdbrnwsk** [comment]
Right... It's OK only if it applies the "overdue" notification; we don't really want to send notifications like "your goal is due in 3 days" when it's already overdue.

**Comment by karolsojko** [comment]
It applies to everything. So this is the scenario:
- I get a notification about due or overdue card
- someone fixes a bug in the application and the new version is deployed to the server
- I get the same notification once again

that should not happen

**Comment by jkbdbrnwsk** [comment]
Yep. Would be fantastic if one of you, Mighty Devs, could fix this one as soon as possible. :) Thank you!

**Comment by karolsojko** [comment]
should be fixed after @theanxy PRs

**Comment by jkbdbrnwsk** [comment]
Thanks @karolsojko, much much much appreciated!
