### ISSUE TITLE
E-mail sender's name

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#118]
Pleace replace "Unleash Your Path!" with "Unleash Bot"

**Comment by karolsojko** [comment]
that could potentially end up in spam as `Bot` is probably on almost all antispam filters ;)

**Comment by theanxy** [comment]
Yeah, good point @karolsojko. However, since the sender has the same domain name as the recipient, I hope Gmail would be more forgiving?

_I'm aware that it's dead simple to fake sender's domain name and Gmail's spam filters are probably more sophisticated than that :stuck_out_tongue: Let's try it_
