### ISSUE TITLE
Display optional messages when added

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#123]
If an Unleasher chooses to add an optional message when marking a card as achieved, this message should be displayed… somewhere here (and perhaps in italics… feel free to experiment :) ): https://www.dropbox.com/s/goj4kp9uuljucbk/Screenshot%202016-03-08%2014.35.27.png?dl=0

**Comment by karolsojko** [comment]
Closing all 1.x issues - we're moving to 2.x
