### ISSUE TITLE
Control account levels from within the app

### ISSUE THREAD

**Issue by theanxy** [x-team/unleash#13]

**Comment by singerxt** [comment]
I'm on it.

**Comment by singerxt** [comment]
Oh.. now I noticed this ticket is assigned to you @theanxy sorry.

**Comment by kbdbrnwsk** [comment]
Please contact @theanxy for the guidelines.

**Comment by karolsojko** [comment]
Should this be closed @theanxy @jkbdbrnwsk ?

**Comment by theanxy** [comment]
Do we still want to be able to control whether someone has admin rights from within the app?

**Comment by karolsojko** [comment]
maybe a question to @jkbdbrnwsk ?

**Comment by jkbdbrnwsk** [comment]
@theanxy @karolsojko This was previously controlled from within Firebase itself, now that we are going to abandon it :D, it would probably make sense to add a possibility to control account levels from within the app.

**Comment by theanxy** [comment]
Yeah, I agree, especially since the switch to microservices makes Kuba unable to control this now that it's not accessible from within the firebase panel. In that case let's keep this open. 

Can we already control this flag via the API? In that case it should be the matter of adding a checkbox to user's page visible to admins only

**Comment by karolsojko** [comment]
Closing all 1.x issues - we're moving to 2.x
