### ISSUE TITLE
"Add resource" form is available, saving form results in "Permission denied"

### ISSUE THREAD

**Issue by jedrzej** [x-team/unleash#134]
I tried to add some resources to Laravel skill. I can access the "Add resource" form, but when I save it, I'm getting the following warning in the console and the resource does not get saved:

> FIREBASE WARNING: set at /resources/-KDn0Tmec0ewR7e6aGRv failed: permission_denied

**Comment by jkbdbrnwsk** [comment]
Thank you, @jedrzej!

Gents, I somehow totally missed it. It's quite an urgent one. Can we please have this bug fixed at your earliest convenience, @theanxy @karolsojko?

**Comment by karolsojko** [comment]
Fixed
