### ISSUE TITLE
Ability to edit cards that have been placed on a path

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#135]
If you want to edit a card, you basically need to delete it and create a new, correct one in place of the old one. Would coding the option to edit cards that have been already placed on a path take much time? If yes, we can leave this feature for the React version; but if it should not consume much time - I would appreciate. :)

Editable data: card name, card description, level

**Comment by karolsojko** [comment]
Fixed by https://github.com/x-team/unleash/commit/e4b93479794d036443a69668784048f77ff89632
