### ISSUE TITLE
Export existing templates to Goals API

### ISSUE THREAD

**Issue by karolsojko** [x-team/unleash#139]
Export the current data of templates to Goals API so it can used in the app

**Comment by jkbdbrnwsk** [comment]
Great deal of those templates is out of date (they are from the time when it was not possible to add unique cards directly to paths; you had to create a template first - and then add it to a path; very often such cards were not used anymore). If you want to suspend work on this, I could delete the templates that most likely won't be used any more.

**Comment by karolsojko** [comment]
@jkbdbrnwsk ok - preparing the migration script will take me some time - you can clear out the templates in the meantime
