### ISSUE TITLE
Validate access to pages at routes level

### ISSUE THREAD

**Issue by theanxy** [x-team/unleash#14]
Currently we validate whether the user has access to a given admin page in page’s controller. This is not ideal: the controller shouldn’t even be initialised if given user doesn’t have admin rights.

**Comment by kbdbrnwsk** [comment]
Please contact @theanxy for the guidelines.

**Comment by karolsojko** [comment]
this is fixed now - Now it only loads the controller when you're authenticated. Can we close this @theanxy ?

**Comment by theanxy** [comment]
Yup, looks good
