### ISSUE TITLE
Adding new goals to paths is not possible

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#145]
Gents, a bug with a high priority :) It's not possible to add new cards to paths. After clicking the "Add" button, the interface freezes. Please take a look at the screenshot. Thanks!

https://www.dropbox.com/s/9jv64u9kb3aix8u/Screenshot%202016-04-13%2016.21.05.png?dl=0

**Comment by karolsojko** [comment]
Fixed by https://github.com/x-team/unleash/pull/146
