### ISSUE TITLE
The bot icon is gone on Slack

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#152]
Please fix :) https://www.dropbox.com/s/vfqyiipvp4nlrl1/Screenshot%202016-05-02%2013.00.16.png?dl=0

**Comment by bernardodiasc** [comment]
I saw this bug yesterday with Howdy in other Slack channel. Today is normalised. Maybe it's the same issue.

**Comment by jkbdbrnwsk** [comment]
Yep, thanks @bernardodiasc!
