### ISSUE TITLE
New comments flag doesn't go off

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#153]
after the card has been clicked to check out new comments: https://www.dropbox.com/s/rgu3wozn7qx52yv/Screenshot%202016-05-02%2021.35.12.png?dl=0

**Comment by Tade0** [comment]
I have a pull request concerning this, but my code is on top an *ancient* version of the app, so I have to prepare it for merging.

**Comment by karolsojko** [comment]
Fixed by https://github.com/x-team/unleash/issues/157 - cache has to be cleared on your local browser
