### ISSUE TITLE
Grabbing a card in order to rearrange it - makes it invisible

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#154]
As far as I remember you could see the card that's being dragged before. https://www.dropbox.com/s/ulljos86objz0v9/Screenshot%202016-05-03%2011.00.19.png?dl=0

**Comment by karolsojko** [comment]
Went back to the version from 19th January (just after adding Docker) and it looks the same as Today. Agreed with Kuba to close this one.
