### ISSUE TITLE
What's up with Windows95-style buttons? :D

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#158]
Or is it just my crazy computer?

https://www.dropbox.com/s/ftf8jrxwbb75dva/Screenshot%202016-05-03%2013.00.58.png?dl=0

**Comment by karolsojko** [comment]
@jkbdbrnwsk : looks fine to me - https://www.dropbox.com/s/b3cgmnjiwmup8z5/Screenshot%202016-05-04%2010.18.02.png?dl=0

can you verify again ?

**Comment by jkbdbrnwsk** [comment]
It must my computer then... ; _ ; Looks like it might be about time to wipe the system and do a fresh installation.
