### ISSUE TITLE
Looks like every "quick card" created becomes also a "template". It should not be the case.

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#159]

**Comment by karolsojko** [comment]
@jkbdbrnwsk can you gives steps to reproduce? I've tried something like this:

1. Went to edit path
2. Added a quick card "Karol test4"
3. Went to templates 
4. Don't see any "Karol test4" template

**Comment by jkbdbrnwsk** [comment]
After going through templates in order to delete them, I was pretty sure I found some cards that once were added as "quick cards".

Can't reproduce this either now, so looks like the bug is gone. If it ever existed... :-x

Closing, thanks.
