### ISSUE TITLE
Can't remove due date

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#162]
If I remove "due date" from a card on staging, the "number of days left" icon indeed disappears, but refreshing the profile brings everything back. Bot also keeps sending reminders.

**Comment by jkbdbrnwsk** [comment]
The bug is still present (was testing with cache disabled).

**Comment by karolsojko** [comment]
@jkbdbrnwsk should be working now - can you check again ?

**Comment by jkbdbrnwsk** [comment]
All good now, thanks.
