### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by svenbergryen** [x-team/unleash#164]
I've tried Chrome, Incognito and Firefox. After I enter my x-team.com credentials, I'm not logged in.

**Comment by jkbdbrnwsk** [comment]
Thanks, @svenbergryen. @karolsojko, would you be so kind to investigate with Sven once you have a spare moment?

**Comment by karolsojko** [comment]
sure 👍  :) I'll get back to this when I'm finished implementing Profiles API :)

**Comment by jkbdbrnwsk** [comment]
Thank you!

**Comment by jkbdbrnwsk** [comment]
I am actually having the same problem now.

Maybe somehow related to this: https://www.dropbox.com/s/3bz7kmftw2icgco/Screenshot%202016-05-13%2012.57.00.png?dl=0

**Comment by jkbdbrnwsk** [comment]
Update on this bug: looks like the app indeed will log you in... but after a while. The login process seems to be happening "in the background", so user may indeed think that nothing is going on once he or she clicks the login button. Everything looks exactly the same after doing so. Please investigate. :)

**Comment by jkbdbrnwsk** [comment]
Magically self-resolved.
