### ISSUE TITLE
Set up a staging server

### ISSUE THREAD

**Issue by theanxy** [x-team/unleash#17]

**Comment by joshwnj** [comment]
ok @theanxy, getting there: http://staging.unleash.x-team.com/

- set up /var/www/staging.unleash directory on fry
- modified the `update` script to remove hardcoded directory, so it will work in both places
- also `update` script now looks for a `setup-env` file (in the same directory, not committed to git) which contains environment specific vars.  If we have any passwords or secret API keys this is a good place to store them, as we don't have to commit to the repo.  Example of what this file looks like:

```
export UNLEASH_ENV=staging
```
- I also set up a separate deploy target. So once you've added that new remote to your local repo, you can `git push deploy-staging master`.

Let me know when https://github.com/x-team/unleash/commit/fec6e54 is in master so we can try it out.

**Comment by theanxy** [comment]
Looking good! Thanks!

TODO: authorize staging app in Google Apps.

**Comment by theanxy** [comment]
Both staging and production have been set up and are fully working.

I wiped out all data in production except admin profiles.

The data in staging remains as is for testing purposes.
