### ISSUE TITLE
Change the format of author's name

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#172]
Instead e-mail's username, please display Firstname Lastname: https://www.dropbox.com/s/clg4ew87ivzt057/Screenshot%202016-05-20%2021.06.58.png?dl=0

**Comment by karolsojko** [comment]
Fixed by https://github.com/x-team/unleash/pull/173

@jkbdbrnwsk - unfortunately already existing comments will display author's username - all future ones will display full name
