### ISSUE TITLE
Change constants replacing

### ISSUE THREAD

**Issue by karolsojko** [x-team/unleash#175]
The file `constants.js` should not be overwritten - should be created only if does not exist

**Comment by Tade0** [comment]
I'm curious: What value does this change bring?

**Comment by karolsojko** [comment]
I have to always type the APIs urls when I do `docker-compose up -d` because it replaces the files with empty values

**Comment by Tade0** [comment]
Oh, that. :D I spent an hour or so yesterday trying to figure this one out.

Adding an `.env` file solved this for me though:
https://docs.docker.com/compose/compose-file

**Comment by karolsojko** [comment]
Closing all 1.x issues - we're moving to 2.x
