### ISSUE TITLE
Ability to change icons on cards

### ISSUE THREAD

**Issue by ryanchartrand** [x-team/unleash#18]
Currently, the default icons are ninjas, but we want to be able to assign custom icons for each card. These icons should be font icons (I believe @theanxy has already picked some font packages out).

**Comment by singerxt** [comment]
@ryanchartrand , @theanxy 

Hello I'm wonder about one extra option. Do we wan't option to upload custom icons (in .png format) or predefined icons are enough ?

One note about implementation if we want this extra option. We using firebase I doubt we can store images there. My suggestion is store images here http://cloudinary.com/ - I believe free option is enough for unleash app.

**Comment by ryanchartrand** [comment]
Predefined would be the first iteration.

On Sat, Feb 28, 2015 at 11:28 AM, Mateusz <notifications@github.com> wrote:

> @ryanchartrand <https://github.com/ryanchartrand> , @theanxy
> <https://github.com/theanxy>
>
> Hello I'm wonder about one extra option. Do we wan't option to upload
> custom icons (in .png format) or predefined icons are enough ?
>
> One note about implementation if we want this extra option. We using
> firebase I doubt we can store images there. My suggestion is store images
> here http://cloudinary.com/ - I believe free option is enough for unleash
> app.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/x-team/unleash/issues/18#issuecomment-76541493>.
>



-- 


Ryan Chartrand
CEO | X-Team LLC | Los Angeles
ryan@x-team.com | 310-866-8382

**Comment by singerxt** [comment]
make sense ;-)

**Comment by singerxt** [comment]
https://github.com/x-team/unleash/pull/28 ready for review and merge

**Comment by singerxt** [comment]
https://github.com/x-team/unleash/pull/29

**Comment by theanxy** [comment]
Can we make it more bulletproof by showing a default icon if no custom icon is set? This is currently the case on prod. @singerxt

**Comment by singerxt** [comment]
@theanxy Yes definitely we should do that I'll fix that thanks!

**Comment by kbdbrnwsk** [comment]
I would also decrease the size of thumbnails a little bit. :)

![2015-03-11_1907](https://cloud.githubusercontent.com/assets/7212882/6603458/99d877c2-c822-11e4-85d2-b2f729f4d1c1.png)

**Comment by kbdbrnwsk** [comment]
...and also align'em properly. ;)

![2015-03-11_1935](https://cloud.githubusercontent.com/assets/7212882/6604019/e31de644-c825-11e4-9d39-adf968300b5b.png)

**Comment by singerxt** [comment]
https://github.com/x-team/unleash/pull/43

**Comment by singerxt** [comment]
https://github.com/x-team/unleash/pull/51
