### ISSUE TITLE
Editing cards placed on a Path

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#192]
Please add an ability to edit cards that have been already placed on a Path.

**Comment by karolsojko** [comment]
duplicate of https://github.com/x-team/unleash/issues/135 ;) ?

**Comment by jkbdbrnwsk** [comment]
Lol, forgot I created a ticket for this... 3 months ago. ;) Would appreciate implementing such option at your earliest convenience. ;)

**Comment by karolsojko** [comment]
Will close this one and continue in #135
