### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by karolsojko** [x-team/unleash#206]
Add tests

example implementation: https://egghead.io/courses/react-testing-cookbook

**Comment by szymonmichalak** [comment]
Do you want to use Shallow Rendering? I have an experience with Karma + Mocha + Rewire and it works really well :-)

**Comment by karolsojko** [comment]
@szymonmichalak that is a great idea :) If you could setup tests for this then it would be cool.

I think the definition of done for this issue would be to have just one test running f.e. for skills list, and then we will make adding tests in every PR a necessity ;)

**Comment by szymonmichalak** [comment]
I started working on that, already added necessary dependencies: https://github.com/x-team/unleash/tree/config/karma-testing

Still need to fix some errors during karma start.
