### ISSUE TITLE
Fix list of skills appearance

### ISSUE THREAD

**Issue by karolsojko** [x-team/unleash#210]
The skills page shows a list of skills - they are already loading from the API, but the left navigation bar (Drawer) overlays them so the names of skills are not visible. Adjust the UI so the list is clearly visible. 

http://www.material-ui.com/ - might be helpful

In general the layout should look something like this:

![zrzut ekranu 2016-07-29 o 10 04 52](https://cloud.githubusercontent.com/assets/311058/17241781/f70e8b86-5573-11e6-85e5-3131512b8954.png)

**Comment by karolsojko** [comment]
This is how it looks now :)

![zrzut ekranu 2016-07-29 o 10 09 59](https://cloud.githubusercontent.com/assets/311058/17241920/b17924c2-5574-11e6-9467-7c2fb88fea70.png)

**Comment by szymonmichalak** [comment]
PR #218
