### ISSUE TITLE
Create a config file

### ISSUE THREAD

**Issue by karolsojko** [x-team/unleash#212]
We need a config file to store variables used by the app, the requirements are:

- the file has to be an example that can be copied to the main file. So for example in the root directory there would be `config.dist.js` that has to be copied to `config.js` in order for the app to work.
- the `config.js` has to be added to gitignore so that it doesn't get commited and everyone can change their config locally 
- as first config variable put SKILLS_API_URL in it and replace `http://skills.unleash.x-team.com/api/v1/skills.json` in `SkillActions.js` with using that config variable
- Config has to work in a way that allows replacing it's values with environment variables. So for example if I have a SKILLS_API_URL environment variable set then it will override the value of config.

**Comment by rmariuzzo** [comment]
I want to be assigned to this one @karolsojko, please.

**Comment by rmariuzzo** [comment]
Hey @karolsojko! I'm working on this right now.
