### ISSUE TITLE
Cards sometimes not aligned properly on first visit

### ISSUE THREAD

**Issue by kbdbrnwsk** [x-team/unleash#22]
Sometimes, when profile is loaded for the first time, cards in the last row are not aligned properly. Refresh helps.
![2015-03-02_0934](https://cloud.githubusercontent.com/assets/7212882/6437456/8466dbbe-c0bf-11e4-941c-c2a784a118c1.png)

**Comment by singerxt** [comment]
I can't reproduce this issue. Can I know browser and breakpoint ?

**Comment by kbdbrnwsk** [comment]
Chrome 40, e.g. 1680px.

**Comment by singerxt** [comment]
Ok thanks :D

**Comment by kbdbrnwsk** [comment]
Please make sure pathbg.js works well.

![zrzut ekranu 2015-03-04 21 46 20](https://cloud.githubusercontent.com/assets/7212882/6493077/7002da1a-c2b8-11e4-8d4b-5f5bc904d288.png)

**Comment by theanxy** [comment]
Fixed the issue with card alignment, I can no longer reproduce. The path offset has been updated, too. Please confirm on staging. @kbdbrnwsk

**Comment by kbdbrnwsk** [comment]
Thanks, @theanxy ! Can't reproduce the issue either, but as it was quite random, I will let you know if it appears again. For now - let's deploy the fix to production. Thank you!
