### ISSUE TITLE
Fix live webpack reloading with Docker

### ISSUE THREAD

**Issue by karolsojko** [x-team/unleash#221]
Fix the issue that on Docker webpack doesn't get triggered about changes on files and doesn't live reload the build process

**Comment by karolsojko** [comment]
I think it works with Docker For Mac. Not so much for Docker Toolbox though

**Comment by diegodurli** [comment]
It's not working on Docker for Mac too @karolsojko!
Will be glad to take a look at it if you want!

**Comment by karolsojko** [comment]
It's open for grabs 👍

**Comment by karolsojko** [comment]
tested now - livereload is working for me on Docker For Mac (although it might take some time for the change to be discovered).

Can anyone else confirm if this works - @kdemoya @szymonmichalak @rmariuzzo @williamcabrera4 @jacekelgda ?

**Comment by williamcabrera4** [comment]
Tested now and works with `Docker for Mac` for the version `Version 1.12.1 (build: 12133)`

**Comment by szymonmichalak** [comment]
I checked today with `Version 1.12.1 (build: 12133)` (Docker for Mac), doesn't work for me :-(

**Comment by szymonmichalak** [comment]
But there is one improvement - if I change something, I only need to refresh the browser to see changes. Before, I had to restart `docker-compose up`...

**Comment by karolsojko** [comment]
hmm that is what I expected @szymonmichalak - the recompiling of the sources. I don't think it's capable of reloading the browser - maybe some research is needed into that
