### ISSUE TITLE
Load User Paths from direct URL

### ISSUE THREAD

**Issue by kdemoya** [x-team/unleash#232]
As of now, getting the user ID for the API calls depends on `ProfileActions.js` to pull the list of all profiles and then we can get the ID for the profile we want.

When hitting a url directly i.e. `/profiles/kelvin.demoya` we don't have the list of users available as profiles aren't loaded. Best approach would be getting data from the API with the username instead of the ID.

**Comment by karolsojko** [comment]
agreed with @kdemoya that it would be best to refactor the app to have urls like `/profiles/{userId}` instead of `/profiles/{userName}` since ProfilesAPI is independent of user data and includes only simple ids.
