### ISSUE TITLE
Rearranging cards leads to some unexpected results :P

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#235]
So I wanted to bring some more order into one of paths, namely Ardi's. Trying to rearrange the position of one of the cards... all of a sudden brought added a whole Rubens' path to Ardi's profile. Fortunately - just temporary, only in the admin panel. Rubens' path was the one I was browsing earlier (didn't enter the admin panel).

Take a look, please: http://d.pr/i/1jJQP

**Comment by jkbdbrnwsk** [comment]
Update: looks like Droplr didn't record the whole thing... Tried to reproduce the bug, but this time an attempt to rearrange cards only lead to creating another empty path.

**Comment by karolsojko** [comment]
@jkbdbrnwsk I've tried to reproduce this one on different profiles but couldn't - maybe it's some kind of a cache thing - does it still happen to you?

**Comment by jacekelgda** [comment]
I have some problems with rearranging cards as well. 
I created first card in a path, then second (lvl1, lvl2) and when I created third card (lvl3) it jumped between two (lvl1,lvl3,lvl2). Impossible to rearrange, even when I remove and add again does the same.

**Comment by jkbdbrnwsk** [comment]
Yep... and it's most likely not related to cache (had it disabled when trying again).

**Comment by karolsojko** [comment]
Closing all 1.x issues - we're moving to 2.x
