### ISSUE TITLE
Parameter 'is_achieved' missing?

### ISSUE THREAD

**Issue by kbdbrnwsk** [x-team/unleash#24]
According to what Wojtek says, cards should have 'is_achieved' parameter (with 'true' or 'false'). Seems it's missing - both in old and newly created cards.
![2015-03-02_0947](https://cloud.githubusercontent.com/assets/7212882/6437632/aac47cd8-c0c1-11e4-891f-2c63f7f21ecf.png)

**Comment by theanxy** [comment]
is_achieved is only added when it's true - if it's absent, it defaults to false. I guess we could create a new issue to fix the 'mark as achieved button' - it's a key part of functionality.

**Comment by kbdbrnwsk** [comment]
Thanks for clarifying!
