### ISSUE TITLE
Can't remove empty card

### ISSUE THREAD

**Issue by jacekelgda** [x-team/unleash#241]
http://unleash.x-team.com/paths/vanja.petreski/
Started creating cards, then something was wrong in levels (they were not in order) so I started ordering them (drag&drop) that was not working but I know there is separate issue for it. Suddenly empty card was created. Now it's impossiburu to remove it. Also when you try to remove it and the create new card nothing happens.

**Comment by jacekelgda** [comment]
Can't get to create empty card in local setup while it is very common in production

**Comment by karolsojko** [comment]
Closing all 1.x issues - we're moving to 2.x
