### ISSUE TITLE
'Mark as achieved' button doesn't work...

### ISSUE THREAD

**Issue by kbdbrnwsk** [x-team/unleash#27]
…partially. It works only on my own profile.

**Comment by singerxt** [comment]
Could you provide more details ?

**Comment by kbdbrnwsk** [comment]
Hey, Mateusz!

Sorry for the confusion, I thought yesterday this functionality works properly, but turns out it doesn't... Thus this ticket.

Please take a look: http://screencast.com/t/3xGsmSlMMxm

**Comment by singerxt** [comment]
Oh I see thanks ! I'll take care about that.

**Comment by singerxt** [comment]
fixed here: https://github.com/x-team/unleash/pull/33

**Comment by kbdbrnwsk** [comment]
Thank you, kind Sir!
