### ISSUE TITLE
Adding resources to skills

### ISSUE THREAD

**Issue by karolsojko** [x-team/unleash#289]
Implement adding resource to a given skill. 

References https://github.com/x-team/unleash/pull/287

API doc: http://skills-staging.unleash.x-team.com/api/doc#post--api-v1-skills-{slug}-resources.{_format}
## Requirements
- [ ] #293

**Comment by jacekelgda** [comment]
Seems like this is already finished by this: https://github.com/x-team/unleash/pull/321

**Comment by karolsojko** [comment]
Fixed by #321
