### ISSUE TITLE
Upvoting resources on a skill

### ISSUE THREAD

**Issue by karolsojko** [x-team/unleash#291]
Implement upvoting resources on a skill

References https://github.com/x-team/unleash/pull/287
## Requirements
- [ ] #293

**Comment by karolsojko** [comment]
API functionality needs to be implemented

**Comment by rmariuzzo** [comment]
Added API requirement in the issue.

**Comment by nicksp** [comment]
Will tackle this issue once i get rights to assign it to myself ;)

**Comment by karolsojko** [comment]
@nicksp https://github.com/x-team/unleash/blob/develop/CONTRIBUTING.md#example

**Comment by nicksp** [comment]
@jacekelgda  In order to finish implementing this feature, there should be added support for `votes` filed on each resource (it's not there yet as i can see) and allowed more HTTP methods on the resource. Here is the error i get atm (am i doing anything wrong?):

![image](https://cloud.githubusercontent.com/assets/579331/23141021/47690410-f7e7-11e6-9205-8180199c297b.png)

**Comment by jacekelgda** [comment]
@nicksp yes, similar to my PR where I needed to add resource author to skills api. Are you willing to add it yourself (PHP) or should we delegate this to someone else ? (I could actually code it for you if you want). In any way Issue in Skills api project should be created. @karolsojko

**Comment by nicksp** [comment]
@jacekelgda If it's fine can you please help me out with this one the first time so that i can learn from it? Moreover I don't have access to the API repo atm...

**Comment by jacekelgda** [comment]
@nicksp will do!

**Comment by jacekelgda** [comment]
@nicksp actually I can see this has been implemented, will check some more https://github.com/karolsojko/skills-api/commit/c2b12da97477bff235c34a172aaf6a4da87b26ad

**Comment by nicksp** [comment]
@jacekelgda hrm.. the api call still says the allowed method is `Delete` only. 
![image](https://cloud.githubusercontent.com/assets/579331/23199920/023c8ce0-f904-11e6-9be3-dcdf6bf54ac5.png)

**Comment by jacekelgda** [comment]
@nicksp on staging it's some older version even so this will not work for sure: http://skills-staging.unleash.x-team.com/api/doc

**Comment by karolsojko** [comment]
should be fixed now on http://skills-staging.unleash.x-team.com/api/doc 

/cc @nicksp @jacekelgda

**Comment by nicksp** [comment]
Yep @karolsojko it's fixed, and PR is ready for review ;-)
