### ISSUE TITLE
Update skill API for resources

### ISSUE THREAD

**Issue by rmariuzzo** [x-team/unleash#293]
Prior to implementing the _Resources feature_ we need to adjust the _Skill API_ with the following changes:
- [x] **Update `Resource` data structure.**
  
  The new structure should look like this:
  
  ``` js
  {
      "id":           123,             // {Number}
      "url":          "http://foo",    // {String}
      "description":  "Lorem Ipsum",   // {String}
      "votes":        [1, 2, 3],       // {Array}     Valid profile ids.
      "type":         'course'         // {String}    Set: <post|course|video|tool|other>
  }
  ```
- [x] **Add `POST: /api/v1/skills/{slug}/resources`.**
  - [ ] Support provision for fields: `url`, `description`, `type`.
  - [ ] Add validation for required fields: `url`, `description`, `type`.
  - [ ] Add validation for valid values for field: `type`. Valid values: `post|course|video|tool|other`.
  - [ ] On success return the full `Resource` object.
  - [ ] On validation error return a 401 response with validation errors.
  - [ ] On other errors return an 500 response.
- [ ] **Update `PUT: /api/v1/skills/{slug}/resources/{id}`.**
  - [ ] Support provision for field: `description`, `votes`.
  - [ ] Add validation for required field: `description`, `votes`.
  - [ ] On success return the full `Resource` object updated.
  - [ ] On validation error return a 401 response with validation errors.
  - [ ] On other errors return an 500 response.

**Comment by karolsojko** [comment]
Closing this one - editing resources should be done on #412
