### ISSUE TITLE
Guest account?

### ISSUE THREAD

**Issue by reod** [x-team/unleash#295]
I'd like to play around but after installation (very clear documented) I get: 
```
Try using an X-Team email address. Not registered.
```
PS: my _gmail_ is: reodowski

**Comment by rmariuzzo** [comment]
@reod: thanks for filing an issue for this. Were you using latest `master` or `develop`?

**Comment by reod** [comment]
`develop` (`d93a07b`)

![screen](http://i.imgur.com/IXTn2EV.png)

**Comment by rmariuzzo** [comment]
Thank you, we will deal with that.
