### ISSUE TITLE
'Sorry, this card doesn't exist' bug on production server

### ISSUE THREAD

**Issue by kbdbrnwsk** [x-team/unleash#30]
Strange bug: info pops up saying card does not exists (even if I can see it clearly ;) ). It fades away after a couple of seconds.

![2015-03-03_1736](https://cloud.githubusercontent.com/assets/7212882/6467058/1be15908-c1cc-11e4-949d-e07b5d05b18e.png)

**Comment by theanxy** [comment]
I can’t reproduce. Is this still relevant?

**Comment by kbdbrnwsk** [comment]
Nope, Mateusz took care of it. :)
