### ISSUE TITLE
Commenting on cards does not work?

### ISSUE THREAD

**Issue by keremgocen** [x-team/unleash#300]
I see this issue was raised before with #161 and #163. 

There is also a PR from @karolsojko on #168 which fixed #161 automatically and later on #163 is also closed with the comment "Should be fixed by #168".

My question is, was it staged into a release at all or got lost in the process? If not, may I take on the issue as it would be a nice and easy start for me?

**Comment by karolsojko** [comment]
Hey @keremgocen thanks for reporting the bug.

Yes that was staged and released - the bug may be up there again. 

Keep in mind that everything you see on unleash.x-team.com is in the branch `support/1.x` and is written in Angular 1.x (we are  currently working on http://staging.unleash.x-team.com/ in the `develop` branch with React.js which will be the Unleash App 2.0). So if you'd like to contribute please create a new branch out of `support/1.x` and make a pull request to that branch.

**Comment by keremgocen** [comment]
Does that mean it's unnecessary to put any effort in 1.0 anymore? Or the same modules will be recycled from 1.0? If you're planning to dump 1.0 codebase, we can close this issue.

**Comment by karolsojko** [comment]
@keremgocen - we are no longer adding features into 1.x but it's still in support mode - so whenever we see some crucial bugs we will fix them - feel free to fix the comment bug if you'd like to take the 1.x for a spin. 

The modules from 1.x won't be recycled in 2.x since the latter one has a different tech stack.

**Comment by karolsojko** [comment]
Closing all 1.x issues - we're moving to 2.x
