### ISSUE TITLE
Wrong order of layers

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#304]
One of the recent fixes has broken another thing. ;) The order of layers seems to be incorrect. Not a big deal, but would appreciate fixing in a spare moment: https://www.dropbox.com/s/c29rhs86dhi264u/Screenshot%202016-11-02%2020.34.02.png?dl=0

**Comment by karolsojko** [comment]
Closing all 1.x issues - we're moving to 2.x
