### ISSUE TITLE
Marking a goal as achieved

### ISSUE THREAD

**Issue by karolsojko** [x-team/unleash#306]
I should be able to mark a goal as achieved.

Basically it comes down to updating the goal with a PUT request and changing the achieved flag.

**Comment by rmariuzzo** [comment]
@karolsojko Only I should be able to mark a personal goal as achieved. I shouldn't be able to do that with other member's goals, right?

**Comment by karolsojko** [comment]
@rmariuzzo at this stage you should be able to mark others as well. Later on we will limit this feature to Unleashers only - but for now marking every goal to keep it simple

**Comment by rmariuzzo** [comment]
@karolsojko thank you! ;)

**Comment by rmariuzzo** [comment]
@karolsojko I'm using the endpoint `PUT /api/v1/paths/{id}/goals/{goalId}.{_format}` to mark a goal as achieved. Is it correct that it returns a list of paths instead of the path specified by the given id?

**Comment by rmariuzzo** [comment]
All right! Here's a preview!

![untitled](https://cloud.githubusercontent.com/assets/439839/20156891/a59d2498-a6a8-11e6-8c58-fec740fdf587.gif)

**Comment by jkbdbrnwsk** [comment]
That's fantastic!
