### ISSUE TITLE
Deleting paths

### ISSUE THREAD

**Issue by karolsojko** [x-team/unleash#314]
As an admin (Unleasher) or the owner of the profile I should be able to remove a given path.

Technically this should do a DELETE request to the given path API url (deleting not yet implemented on the API side).

**Comment by jenriquejr** [comment]
@karolsojko 
first: is this delete endpoint already implemented on the API ?
second: Might be pretty obvious but want to make sure, does this delete endpoint also checks that user removing the path is admin or owner? (API)
