### ISSUE TITLE
Firebase is hackable.

### ISSUE THREAD

**Issue by singerxt** [x-team/unleash#32]
I think we should configure firebase rules for now our configuration looks
```
{
    "rules": {
        ".read": true,
        ".write": true
    }
}
```
so everybody can edit database from browser console.

**Comment by ajgon** [comment]
Also I would recommend to fix authentication, since everybody can log in (not only from x-team domain), i.e.

    new Firebase("https://unleash-app.firebaseio.com").authWithOAuthPopup('google', function() {})

**Comment by theanxy** [comment]
Thanks for the audit @ajgon! We’ll add more security rules ASAP.

**Comment by kbdbrnwsk** [comment]
Please contact @theanxy for the guidelines.

**Comment by szymonmichalak** [comment]
On unleash-app-staging.firebaseio.com I've tested those settings:

```
{
    "rules": {
        ".read": "auth != null",  // READ only for logged-in user
        ".write": "root.child('users').child(auth.uid).child('is_admin').val() == true",  // WRITE only for logged-in user with admin privileges
        "users": {
          "$userID": {
            "cards": {
              "$card": {
                ".write": "auth != null"   // Changing card properties (e.g. updating `unread` counter); adding comments
              }
            },
            "newComments": {
              ".write": "auth != null"
            }
          }
        }
    }
}
```

Please let me know, if it works well for you too :)

**Comment by theanxy** [comment]
Looks good so far, except for the console error in the logged out state.

**Comment by szymonmichalak** [comment]
Logged out state fixed.

After merging #61, the configuration should look like:
{
    "rules": {
        ".read": true,
        ".write": "root.child('users').child(auth.uid).child('is_admin').val() == true",  // WRITE only for logged-in user with admin privileges
        "users": {
          "$userID": {
            "cards": {
              "$card": {
                "comments": {
                  "$comment": {
                    ".write": "auth != null"   // Adding comments for logged-in users
                  }
                },
                "unread": {
                  ".write": "auth != null"   // Changing card properties (e.g. updating `unread` counter)
                }
              }
            },
            "newComments": {
              ".write": "auth != null"   // Adding new comments to user's profile
            }
          }
        }
    }
}

**Comment by theanxy** [comment]
:+1: Good job, let’s continue testing this on staging. If we won’t spot any problems, we’ll be able to apply this on production. cc @kbdbrnwsk

**Comment by kbdbrnwsk** [comment]
Thanks, Gents. Will take a look at staging today.

**Comment by szymonmichalak** [comment]
I've updated the settings on staging just now as mentioned in my previous comment. @kbdbrnwsk please check if this works well for both admin and non-admin users.

**Comment by szymonmichalak** [comment]
UPDATE. Some of the admins have `true` `is_admin` flag, some of them have `1` value. I updated the firebase security options to include that condition as well.

```
{
    "rules": {
        ".read": true,
        ".write": "root.child('users').child(auth.uid).child('is_admin').val() == true || root.child('users').child(auth.uid).child('is_admin').val() == 1",  // WRITE only for logged-in user with admin privileges
        "users": {
          "$userID": {
            "cards": {
              "$card": {
                "comments": {
                  "$comment": {
                    ".write": "auth != null"
                  }
                },
                "unread": {
                  ".write": "auth != null"   // Changing card properties (e.g. updating `unread` counter); adding comments
                }
              }
            },
            "newComments": {
              ".write": "auth != null"
            }
          }
        }
    }
}
```

**Comment by kbdbrnwsk** [comment]
Closing. Thanks!
