### ISSUE TITLE
DatePicker error

### ISSUE THREAD

**Issue by karolsojko** [x-team/unleash#359]
when you go to a profile page, there is an error in the console regarding DatePicker:

https://www.dropbox.com/s/ty78htr8uvtfvcf/Zrzut%20ekranu%202017-02-15%2014.33.00.png?dl=0

**Comment by szymonmichalak** [comment]
When `parameters.dueDate` is undefined / null error appears which makes unable to open modal: 
<img width="726" alt="screen shot 2017-02-18 at 11 45 55" src="https://cloud.githubusercontent.com/assets/6726839/23092640/e0d47ea0-f5cf-11e6-9a57-5640287e93bc.png">
