### ISSUE TITLE
Review Unleash App

### ISSUE THREAD

**Issue by szymonmichalak** [x-team/unleash#374]
As discussed with Unleashers, at the end of our current milestone, I would like to take a moment to review Unleash App to check if there is need to refactor the code, apply the standards we are working on, etc.

**Comment by karolsojko** [comment]
@szymonmichalak the release milestone is finished - we are in the testing phase with @jkbdbrnwsk and @jacekelgda - I think this is a good time to start looking at some refactoring :)
