### ISSUE TITLE
Add form validation

### ISSUE THREAD

**Issue by szymonmichalak** [x-team/unleash#375]
### WIP: Please do not assign and do not work on this task!

Currently forms are not validated at all. User can hit "submit" button with invalid data, which leads to some console / server errors.

If you would like to suggest some validation approach, please add a comment. If it's already there add 👍 . If you have a strong preference, use 👎 as well ;-)

**Comment by szymonmichalak** [comment]
Used many times, never regret it:
https://github.com/jurassix/react-validation-mixin

Built as a HoC, can use different validation strategy, one of my favourite is: https://github.com/jurassix/joi-validation-strategy

**Comment by szymonmichalak** [comment]
Any fans of [redux-form](https://github.com/erikras/redux-form) ?

**Comment by karolsojko** [comment]
Maybe we could https://github.com/kasprownik/react-xform

@kasprownik - is it suitable for this case and stable enough?

**Comment by kasprownik** [comment]
@karolsojko forget it for now :) Work in progress, not production ready
