### ISSUE TITLE
Move component methods to helpers

### ISSUE THREAD

**Issue by szymonmichalak** [x-team/unleash#377]
### WIP: Please do not assign and do not work on this task!

An example: `daysLeft` in [GoalCard.jsx](https://github.com/x-team/unleash/blob/develop/app/components/GoalCard.jsx#L44) component.

I would suggest to move all such methods to separate helper files.

Please react 👍 / 👎 and write some comments!

**Comment by nicksp** [comment]
Definitely worth implementing that. The thing that we use in our current project it having helper files/libs per the component: like all date related functions go into `datesHelper.js` file, text ones - `textHelpers.js`, etc. Allows to navigate around the project much easier and introduce structure into the app codebase.

**Comment by karolsojko** [comment]
All agree - I think this one can be closed @szymonmichalak
