### ISSUE TITLE
Decide on JSDoc comments / author references

### ISSUE THREAD

**Issue by szymonmichalak** [x-team/unleash#379]
### WIP: Please do not assign and do not work on this task!

There are couple of files in the project where JSDoc comments are added ([example](https://github.com/x-team/unleash/blob/3be5b050144d60c6cd77df8aa9902a5cf017c2e3/app/hocs/toggleHOC.jsx#L20)) or author reference ([example](https://github.com/x-team/unleash/blob/3be5b050144d60c6cd77df8aa9902a5cf017c2e3/app/containers/SkillContainer.js#L1)) at the very beginning of the file.

I would suggest to be consistent in that matter. If we want to keep and maintain them, let's add it to the entire project.

Please react 👍 if you feel we should add them to all files or 👎 if we should delete all of them. Please write some comments too!

**Comment by kdemoya** [comment]
There are two different things here:

1. I would vote in favor JSDocs.
2. Author references are not needed, most of them are mine (if not all) because I configured my IDE to automatically do it in the past, I agree on removing them.

**Comment by nicksp** [comment]
Yeah JSDoc is definitely a way to go when it comes to documenting your code. Ad as far as i'm aware of it, author references are not widely used in different projects. As it's more important to have code explanation rather than author of each concrete LOC :)

**Comment by karolsojko** [comment]
This can be closed since everyone agrees - @szymonmichalak right?
