### ISSUE TITLE
Review usage of lodash functions and replace with built-in equivalents

### ISSUE THREAD

**Issue by szymonmichalak** [x-team/unleash#380]
### WIP: Please do not assign and do not work on this task!

In the project we tend to overuse `lodash`, while there is a huge list of supported, built-in equivalents.

Let's stop using `_.map`, `_.reduce`, `_.filter`, etc. while we are able to do the same with plain JS.

Please react 👍 / 👎 and write some comments!

**Comment by kdemoya** [comment]
While that's fair thinking, I don't see the issue on being consistent using lodash, which methods are generally faster than the JS counterparts, btw.

**Comment by szymonmichalak** [comment]
@kdemoya I agree, and it's not only the performance. Native methods are usually not exactly the same as the ones lodash provides (lodash generally provides more features).

The main aim of this issue is to make it more consistent across the project. Maybe I went too far by saying "let's stop using lodash" - I should have say: "Let's decide on when to use lodash and when native methods are enough"

**Comment by dash-** [comment]
I'm still an outsider of this project -- I haven't even seen the source yet.  But my recommendations, if we're going to continue to use lodash, is to always avoid _.map , _.reduce , _.xxx on at least client side apps (and preferably on server-side apps as well, for consistency if nothing else).

In their place, it's preferable to just import each lodash function independently (they're delivered as individual files on purpose, in addition to the "bundled" index file).  Importing function files individually has performance benefits, particularly on the client-side.

import map from 'lodash/map';
import reduce from 'lodash/reduce';
import xxx from 'lodash/xxx'; // where xxx is any lodash function

I think I first saw this in a Dan Abramov video.  I have also seen him post about it on Twitter.  https://twitter.com/dan_abramov/status/605691126549508096?lang=en

Side note: If you're not following @dan_abramov on Twitter, you should be.  He's my favorite developer of 2016 (mostly for stuff he before 2016, like co-authoring Redux, Create React App, React Hot Loader, React DnD, etc).

**Comment by nicksp** [comment]
That's a really great piece of performance-related advice from @dash- ! That's the trick i've been using personally on all my projects recently and it really boosts performance of the app.

Speaking more generally, the advice is: **Use relative file paths**. This works for **almost all node modules** too, not just `lodash`. Simply replace your destructing assignment import statements with local path import statements and see the instant bundle's size reduction :)

So do this:
```js
import concat from 'lodash/concat';
```

instead of this:
```js
import { concat, sortBy, map, sample } from 'lodash';
```

**Comment by szymonmichalak** [comment]
Great comments @dash- and @nicksp! We definitely need to change that in our project.

**Comment by karolsojko** [comment]
I'm 👍 for using lodash. Good comments on the way of using it btw.
