### ISSUE TITLE
Start with empty values when adding resource

### ISSUE THREAD

**Issue by nicksp** [x-team/unleash#384]
Every time you open up a modal to add a new resource it should start with empty fields, not prefilled with previous values (as it is now). It'll benefit the UX of the app, cause when i'm adding a **new** resource i'd like to start from scratch.

**Comment by szymonmichalak** [comment]
**Note:** It might be a good idea to check all the other modals in the app.

**Comment by nicksp** [comment]
@szymonmichalak Yeah for sure worth doing it 👍

**Comment by mccrodp** [comment]
I've started looking at this. I can reproduce @nicksp's bug as in the description, however if you refresh the page, the values are not pre-filled in the modal, they are blank again. So, perhaps this is linked to the fact that the newly added Resources do not display after the "Add Resource" button is selected in the modal.

I'll look closer into this but any info in the meantime is much appreciated to point me in the right direction, or suggest what the ideal behaviour is here.

I imagine we should refresh the display an show the Resources as they are added, then I believe the fields will be blank again.

**Comment by mccrodp** [comment]
I believe this is linked to https://github.com/x-team/unleash/issues/385

**Comment by mccrodp** [comment]
I found this is in `Skill.jsx`, but that's about all I can do for today.

Is the "React Developer Tools" extension useful to debug this? Chrome recommended I download, but it seems to give me the rendered output rather than the source.

**Comment by szymonmichalak** [comment]
> however if you refresh the page, the values are not pre-filled in the modal, they are blank again

@mccrodp just wanted to confirm, that this is correct behaviour. Once you refresh the page, states in reducers are clear out and that's what we expect right now :)

**A small hint here:** I think the best way out here is to just clear the values after submitting the form in the modal. We could also clear on modal close.

In `Skill` component, take a look at this [line](https://github.com/x-team/unleash/blob/develop/app/components/Skill.jsx#L118). And compare it to `AddGoalsModal` [here](https://github.com/x-team/unleash/blob/develop/app/components/AddGoalsModal.jsx#L122). You will see that after submit, form reset is performed.

**Comment by mccrodp** [comment]
Thanks a lot @szymonmichalak, that's a great help. Going to look at this tomorrow :)

**Comment by mccrodp** [comment]
Spent a while at this today, and was a good introduction.

I tried to replicate that of the Goals dialog and tried a few things and went down the rabbit hole a bit, as things are quite new to me. Need more time with it, will look again tomorrow.

For now, this is as far as I think is relevant, so feedback and tips welcome:

````jsx
export function resetResourceDialog() {
  return {
    type: SKILL.ADD_RESOURCE.RESET,
  };
}

export function resourceAdd(skillSlug, resource) {
  return (dispatch) => {
    dispatch({ type: SKILL.ADD_RESOURCE.START });
    return httpClient.post(`${config.skills_api_url}/${skillSlug}/resources.json`, resource)
      .then(() => {
        dispatch(resetResourceDialog());
        updatedSkill => dispatch({ type: SKILL.ADD_RESOURCE.SUCCESS, updatedSkill })
      })
      .catch(errors => dispatch({ type: SKILL.ADD_RESOURCE.FAILURE, errors }));
  };
}
````

I added a new `RESET` type for the resource and tried to call it in `dispatch`, but my syntax is wrong at the moment. I also saw I would need to add this new `REST` entry as a reducer, but not sure how to set up an initial state for this dialog yet.

**Comment by szymonmichalak** [comment]
@mccrodp the first thing that is definitely incorrect are those lines:
```
.then(() => {
    dispatch(resetResourceDialog());
    updatedSkill => dispatch({ type: SKILL.ADD_RESOURCE.SUCCESS, updatedSkill })
})
```

`updatedSkill` is returned from `httpClient.post(..)`, so you would need to change that to:

```
.then((updateSkill) => {
    dispatch({ type: SKILL.ADD_RESOURCE.SUCCESS, updatedSkill });
    dispatch(resetResourceDialog());
})
```

Also, if you could push your changes, we would be able to see what's still wrong / missing and suggest some changes ;-)
