### ISSUE TITLE
Update resources once it's been added

### ISSUE THREAD

**Issue by nicksp** [x-team/unleash#385]
The list of skills' resources should be fetched from the server, once the new resource has been added to the list. At the moment, there is a need to update the list manually (with page refresh) to get the updated list after adding a new resource.

**Comment by szymonmichalak** [comment]
Question: Should we fetch the entire list again or maybe it's possible to just add the response (from POST) to the list?

**Comment by nicksp** [comment]
Should be easy just to asynchronously dispatch an action to fetch the list again once the new item has been added.

**Comment by karolsojko** [comment]
just btw - I think this is not connected to #384

**Comment by mccrodp** [comment]
Yep, that was before I realised they are separate components :smile

**Comment by nicksp** [comment]
@szymonmichalak @mccrodp @karolsojko We can close that issue as this is fixed in the scope of my PR https://github.com/x-team/unleash/pull/387 :)
