### ISSUE TITLE
Slack integration

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#39]
When a card is marked as achieved, there should be an option to send a notification to the #unleash channel.

Additional feature: a possibility to add an optional comment to the notification while marking a card as achieved.

**Comment by kbdbrnwsk** [comment]
This feature has low priority now. All news about Unleashees' successes are being published via Unleash Timeline.

**Comment by kbdbrnwsk** [comment]
Changed the priority to medium. I think sometimes it will make much more sense to push a short info about a small step being completed to Slack, than to write a one- or two-senteced UT blog entry.

Or maybe better... to integrate PtU app with the Unleash Timeline WP itself.

Let's discuss it sometime next week, @Tade0. :)
