### ISSUE TITLE
Upvoting resources 404

### ISSUE THREAD

**Issue by karolsojko** [x-team/unleash#410]
Upvoting a resource on a skill redirects to the 404 page:

http://staging.unleash.x-team.com/skills/symfony

**Comment by szymonmichalak** [comment]
The request goes to: `http://skills.unleash.x-team.com/api/v1/skills/...`. I assume that on production this endpoint is still no there. Btw. shouldn't staging using `skills-staging.unleash...` endpoint?

**Comment by karolsojko** [comment]
the latest skills API wasn't deployed to prod version - fixed now
