### ISSUE TITLE
Slack notification error

### ISSUE THREAD

**Issue by jacekelgda** [x-team/unleash#419]
When I tried to mark goal as achieved under: http://unleash.x-team.com/profiles/102910006051885155614 "GalileoSettingBundle" got an error about slack notification and nothing was pushed to slack channel

<img width="1314" alt="screen shot 2017-03-14 at 12 38 48" src="https://cloud.githubusercontent.com/assets/1003372/23898928/5fd2101e-08b3-11e7-9881-a3a129cf98ce.png">
<img width="310" alt="screen shot 2017-03-14 at 12 38 42" src="https://cloud.githubusercontent.com/assets/1003372/23898933/6355f58e-08b3-11e7-84ff-95d2ce7813fa.png">

**Comment by benf86** [comment]
Similar/same problem, except I didn't get an error message, but rather nothing at all...

![image](https://cloud.githubusercontent.com/assets/4596061/24038792/44290028-0b03-11e7-934c-9da409fda771.png)

**Comment by karolsojko** [comment]
Fixed by: https://github.com/x-team/unleash/commit/d76d258ec3110aeb611409945736ec022efcfceb
