### ISSUE TITLE
Investigate problems with reordering cards

### ISSUE THREAD

**Issue by theanxy** [x-team/unleash#42]
Reordering cards seems problematic on some profiles.

More details: 
reordering cards doesn’t work when the priority of all cards on a profile is the same. This should never be the case. However for some reason Firebase returns inconsistent results when asked for a $priority of given cards. This might be a bug with AngularFire, as doing `curl` returns valid values. Workaround is needed.

**Comment by theanxy** [comment]
Some more problems were discovered. It is being tracked on https://github.com/x-team/unleash/tree/fix-reordering-issues

**Comment by kbdbrnwsk** [comment]
Please contact @theanxy for the guidelines.

**Comment by szymonmichalak** [comment]
@kbdbrnwsk please check, if we can close this issue.

**Comment by kbdbrnwsk** [comment]
Thanks!
