### ISSUE TITLE
Clear due date

### ISSUE THREAD

**Issue by jacekelgda** [x-team/unleash#426]
I would be awesome if we were able to clear due date when it's set. Right now it's impossible.

**Comment by mohamednizar** [comment]
@jacekelgda  Who is working on this issue ? See the attachment . Shall we place the clear button at the end of field ?

![clear_date](https://cloud.githubusercontent.com/assets/8711284/26006352/b6842b84-3759-11e7-854c-495e6744b9e4.png)

**Comment by karolsojko** [comment]
@mohamednizar this one is free :) yes, you can place it like on the screenshot 👍

**Comment by mohamednizar** [comment]
I have made changes and created a pull request, see [https://github.com/x-team/unleash/pull/455](https://github.com/x-team/unleash/pull/455)

**Comment by jkbdbrnwsk** [comment]
Great stuff, thank you for your contribution, @mohamednizar!
