### ISSUE TITLE
Rename "Empty Path" to something more eligant

### ISSUE THREAD

**Issue by mccrodp** [x-team/unleash#429]
"Empty Path" while most likely true on the back end sounds a bit "empty" on the front-end.

<img width="546" alt="screen shot 2017-03-28 at 09 39 09" src="https://cloud.githubusercontent.com/assets/559938/24383835/75d81ce0-139a-11e7-8c24-c79fd2064ea4.png">

Let's call it something like "General Path" or "Miscellaneous Path" as that what it looks like it is. I prefer the former, but if anyone else has any better suggestions, that's great too.

**Comment by karolsojko** [comment]
The thing is that whenever you create a new path then it's called "Empty Path" - so having more than one "General Path" wouldn't make much sense - and also I think "Empty Path" is good since it's prompting to rename it ... which I obviously didn't do 😅

**Comment by mccrodp** [comment]
That makes sense Karol. Maybe everyone from Unleash with these Empty Paths should rename them to General. Not a huge deal though. 

Maybe "Unnamed Path" makes more sense as default string with the info you gave above then, as the paths aren't empty, they are just haven't been given a name.
