### ISSUE TITLE
Replace creating skills with Serverless API

### ISSUE THREAD

**Issue by karolsojko** [x-team/unleash#430]
We have a new Serverless Skills API: https://github.com/x-team/skills-api

You can see the endpoints of the API in here: https://travis-ci.org/x-team/skills-api/builds/216285457#L572

The urls are for the `dev` environment. This task is only about creating skills.

**Comment by diegodurli** [comment]
Hi @karolsojko!

I just tried to replace the skills URL and apparently the server is not allowing CORS requests.

```
Fetch API cannot load https://fy5p532pni.execute-api.us-west-2.amazonaws.com/dev/skills.
No 'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://localhost' is therefore not allowed access.
If an opaque response serves your needs, set the request's mode to 'no-cors' to
fetch the resource with CORS disabled.
```

I can see that the former API endpoint (`http://skills-staging.unleash.x-team.com/api/v1/skills`) was returning the proper `response header`:

`Access-Control-Allow-Origin: http://localhost`

I will send some code on the Serverless API regarding this issue.

**Comment by karolsojko** [comment]
@diegodurli weird - according to this it should have CORS support: https://github.com/x-team/skills-api/blob/develop/serverless.yml#L47

**Comment by karolsojko** [comment]
@diegodurli should be fixed now by this: https://github.com/x-team/skills-api/commit/7abebc4077045f7a13eea576dd9221e5a9bb9a09

**Comment by karolsojko** [comment]
Fixed by https://github.com/x-team/skills-api/pull/1
