### ISSUE TITLE
Issue on docker-compose up

### ISSUE THREAD

**Issue by mohamednizar** [x-team/unleash#454]
I'm setting up the unleash on my local environment to contribute on the project.On `docker-compose up` the build was terminated with the following error logs.

`0 info it worked if it ends with ok`
`1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]`
`2 info using npm@3.10.3`
`3 info using node@v6.5.0`
`4 verbose run-script [ 'prestart', 'start', 'poststart' ]`
`5 info lifecycle unleash@2.0.0~prestart: unleash@2.0.0`
`6 silly lifecycle unleash@2.0.0~prestart: no script for prestart, continuing`
`7 info lifecycle unleash@2.0.0~start: unleash@2.0.0`
`8 verbose lifecycle unleash@2.0.0~start: unsafe-perm in lifecycle true`
`9 verbose lifecycle unleash@2.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/var/www/unleash/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
`10 verbose lifecycle unleash@2.0.0~start: CWD: /var/www/unleash`
`11 silly lifecycle unleash@2.0.0~start: Args: [ '-c', 'babel-node devServer.js' ]`
`12 silly lifecycle unleash@2.0.0~start: Returned: code: 1  signal: null`
`13 info lifecycle unleash@2.0.0~start: Failed to exec start script`
`14 verbose stack Error: unleash@2.0.0 start: `babel-node devServer.js``
`14 verbose stack Exit status 1`
`14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)`
`14 verbose stack     at emitTwo (events.js:106:13)`
`14 verbose stack     at EventEmitter.emit (events.js:191:7)`
`14 verbose stack     at ChildProcess.<anonymous> `(/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
`14 verbose stack     at emitTwo (events.js:106:13)`
`14 verbose stack     at ChildProcess.emit (events.js:191:7)`
`14 verbose stack     at maybeClose (internal/child_process.js:877:16)`
`14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)`
`15 verbose pkgid unleash@2.0.0`
`16 verbose cwd /var/www/unleash`
`17 error Linux 4.4.0-53-generic`
`18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"`
`19 error node v6.5.0`
`20 error npm  v3.10.3`
`21 error code ELIFECYCLE`
`22 error unleash@2.0.0 start: `babel-node devServer.js``
`22 error Exit status 1`
`23 error Failed at the unleash@2.0.0 start script 'babel-node devServer.js'.`
`23 error Make sure you have the latest version of node.js and npm installed.`
`23 error If you do, this is most likely a problem with the unleash package,`
`23 error not with npm itself.`
`23 error Tell the author that this fails on your system:`
`23 error     babel-node devServer.js`
`23 error You can get information on how to open an issue for this project with:`
`23 error     npm bugs unleash`
`23 error Or if that isn't available, you can get their info via:`
`23 error     npm owner ls unleash`
`23 error There is likely additional logging output above.`
`24 verbose exit [ 1, true ]`

**Comment by karolsojko** [comment]
@mohamednizar did you install all dependencies by running `docker-compose run web yarn` ?

**Comment by mohamednizar** [comment]
@karolsojko  Yes , I have installed all dependencies.

**Comment by mohamednizar** [comment]
@karolsojko  issue was there are no config for local environment. I added a config.local.js.
