### ISSUE TITLE
Fix JS error for logged out users on prod

### ISSUE THREAD

**Issue by theanxy** [x-team/unleash#46]
![screen shot 2015-03-31 at 13 52 05](https://cloud.githubusercontent.com/assets/92843/6918310/3e556a6e-d7ad-11e4-9dac-20def8740056.png)

**Comment by jkbdbrnwsk** [comment]
Has this one been fixed, @theanxy? Can I close? :)

**Comment by Tade0** [comment]
Fixed with #102.
