### ISSUE TITLE
SHOW LESS/SHOW MORE (steps)

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#460]
Clicking on the SHOW LESS should fold steps under a goal. SHOW LESS changes to SHOW MORE (and the arrow inverts). Clicking SHOW MORE unfolds steps under a goal.

![image](https://cloud.githubusercontent.com/assets/7212882/26693328/0f8da41c-4704-11e7-8151-0d094e80ca4f.png)

**Comment by karolsojko** [comment]
Fixed by https://github.com/x-team/unleash/pull/478
