### ISSUE TITLE
Webpack flow unleash styles errors on install

### ISSUE THREAD

**Issue by jacekelgda** [x-team/unleash#476]
We have created separate styles repo: https://github.com/x-team/unleash-styles
It has also been published as npm pacakge: https://www.npmjs.com/package/unleash-styles

when I try to install this package in this project using yarn: `yarn add unleash-styles` I am getting such erros:

<img width="1082" alt="screen shot 2017-07-18 at 16 22 27" src="https://user-images.githubusercontent.com/1003372/28322072-5d882cbe-6bd5-11e7-884f-c3542af935cf.png">

list of errors is long. I get an error for each component in the package.

**Comment by joshi-mehul** [comment]
Hi @jacekelgda I checked you're commit, you're removing flow to get rid of errors, should I help you fix this? I liked this issue.

**Comment by szymonmichalak** [comment]
Thanks @joshi-mehul for your interest! It turned out to be a problem of `unleash-styles` package itself and it's already solved. Closing this issue.

**Comment by joshi-mehul** [comment]
@szymonmichalak  if anything else let me know, I would love to contribute.
