### ISSUE TITLE
Adding new cards sometimes breaks a path

### ISSUE THREAD

**Issue by kbdbrnwsk** [x-team/unleash#48]
Not sure what causes this problem (previosly we thought it's because of templates not being fully loaded), but sometimes dragging a template to dev's path (in 'Edit path' panel) breaks the cards that are already placed there. Those cards loose all atributes, and become '0' in the database.

Please touch base with @theanxy to get some potential directions on how the bug can be fixed.

**Comment by kbdbrnwsk** [comment]
Fixing this bug has the highest priority.

**Comment by theanxy** [comment]
A little more background on this:

to add a card, we’re using angularfire’s $add method which in theory shouldn’t affect other cards. This leads me to the conclusion that this might be a problem with angularfire library.

Firebase released Angularfire 1.x recently (with breaking changes) and I think the best would be to just upgrade the library and our services.

**Comment by kbdbrnwsk** [comment]
Seems this bug has been fixed on staging, can I please ask to have the fixed pushed to production? Thanks!
