### ISSUE TITLE
Development status

### ISSUE THREAD

**Issue by Eduardoveras** [x-team/unleash#481]
Is this project officially deprecated by the team?

**Comment by jacekelgda** [comment]
Hi @Eduardoveras ! For now this project is on hold. Are you interested in contributing ?

**Comment by Eduardoveras** [comment]
Yes! I might make a fork and work on that

**Comment by jacekelgda** [comment]
You are more then welcome. 
If you would like to work on a project with React - this is a very good place for that.

Although there is a very interesting slack integration project that is being currently developed that I can point direction to (Node.js). It bases it's functionality on unleash app.

**Comment by jacekelgda** [comment]
pls unassign me from here
