### ISSUE TITLE
Install WordPress for the Timeline feature

### ISSUE THREAD

**Issue by kbdbrnwsk** [x-team/unleash#53]
@joshwnj, may I please ask to have another WordPress for the new Timeline feature installed on X-Team server?

We are going to have it then iframed at the unleash.x-team.com landing page (after user logs in).

Will drop you all the necessary files on Slack.

Thanks!

**Comment by joshwnj** [comment]
@kbdbrnwsk is `unleash-timeline.x-team.com` good for the subdomain?

**Comment by kbdbrnwsk** [comment]
@joshwnj Perfect! Thanks a million!

**Comment by joshwnj** [comment]
Great, thanks. Made some progress on this today, will continue tomorrow.

**Comment by joshwnj** [comment]
Details:

- site: http://unleash-timeline.x-team.com/
- repo: https://github.com/x-team/unleash-timeline

@kbdbrnwsk who should I give the WP admin password to? You?

**Comment by kbdbrnwsk** [comment]
@joshwnj Yes, please :)

Thanks a lot for helping with this!!

**Comment by joshwnj** [comment]
Done - yw :)

**Comment by kbdbrnwsk** [comment]
Cheers!
