### ISSUE TITLE
Add 'Timeline' link to header

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#54]
![screenshot 2015-05-15 22 06 22](https://cloud.githubusercontent.com/assets/7212882/7664796/cbfa02de-fb4e-11e4-933e-3d5709eedd70.png)

**Comment by karolsojko** [comment]
Should this be closed in favor of #58 @jkbdbrnwsk ?

**Comment by jkbdbrnwsk** [comment]
Replied in #58. ;)

**Comment by karolsojko** [comment]
Closing all 1.x issues - we're moving to 2.x
