### ISSUE TITLE
Add the ability to place cards with the same titles and levels

### ISSUE THREAD

**Issue by kbdbrnwsk** [x-team/unleash#57]
Currently it is not possible to add two or more cards with the same title and level to a path (once you drag'n'drop a card with level, say, 1, other cards with level 1 disappear from the right column). Please make it possible. :)

**Comment by szymonmichalak** [comment]
@kbdbrnwsk please check, if we can close this issue.

**Comment by kbdbrnwsk** [comment]
Thanks!
