### ISSUE TITLE
Landing page: Timeline

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#58]
After user logs in, WP Timeline should be displayed instead the Paths grid. Please add the Timeline in an iframe.

![screenshot 2015-05-16 10 52 19](https://cloud.githubusercontent.com/assets/7212882/7667368/d58144dc-fbb9-11e4-9afd-37dca1348f43.png)

**Comment by jkbdbrnwsk** [comment]
Hey @Tade0 @theanxy @karolsojko, I'd like to integrate Unleash Timeline with unleash.x-team.com. What would be the best approach to do that? A simple iframe, or should we move the whole Wordpress to Digital Ocean where the interface is hosted now?

**Comment by karolsojko** [comment]
It doesn't matter if the Wordpress is on DigitalOcean ... it's a matter of styling the iframe I guess

**Comment by jkbdbrnwsk** [comment]
Yep, I was just thinking if it's better to have everything "in one place".

Anyway, Tadeusz is also upvoting the iframe. :)

**Comment by Tade0** [comment]
I guess if this were the only place where the timeline appeared then with some work we could always get rid of WordPress entirely and make it part of the app. :)

**Comment by karolsojko** [comment]
Created a draft for this on `unleash_timeline` branch https://github.com/x-team/unleash/tree/unleash_timeline

@theanxy can you have a look?

**Comment by theanxy** [comment]
I took a look. Looks good so far, will need to take care of adjusting iframe's height in sync with the WP instance, e.g. using https://viget.com/extend/using-javascript-postmessage-to-talk-to-iframes. 

Who can grant me access to the WP theme for the timeline? /cc @jkbdbrnwsk

**Comment by jkbdbrnwsk** [comment]
@theanxy - please ask Josh

**Comment by jkbdbrnwsk** [comment]
BTW: now that we will use Timeline only for "big stories" (thus writing there less often), I'd prefer to keep the avatar grid on landing - as it's right now.

Let's add Timeline to the top menu, linking to a site with an iframe.

**Comment by theanxy** [comment]
:+1:

**Comment by karolsojko** [comment]
Closing all 1.x issues - we're moving to 2.x
