### ISSUE TITLE
Change border color accordingly to the possibility of dropping a card

### ISSUE THREAD

**Issue by kbdbrnwsk** [x-team/unleash#6]
If card can be dropped, display green border; otherwise - red.
![2015-01-07_1956](https://cloud.githubusercontent.com/assets/7212882/5651402/5f233d12-96a7-11e4-8703-408108b4c487.png)

Also - if someone attempts to drop a card when it's not possible, a short message could be displayed.

**Comment by theanxy** [comment]
We’re only showing cards that can be dropped currently. Closing.
