### ISSUE TITLE
Card info sidebar

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#60]
Remove "Steps I'm taking:".

Create better looking buttons.

![screenshot 2015-05-16 11 12 29](https://cloud.githubusercontent.com/assets/7212882/7667451/f4a324ae-fbbc-11e4-99e7-41a70baf47ce.png)

Sort out the order of layers.

![screenshot 2015-05-16 11 16 32](https://cloud.githubusercontent.com/assets/7212882/7667453/14c0b4ea-fbbd-11e4-9975-1c9bef207588.png)

**Comment by kbdbrnwsk** [comment]
Thanks!
