### ISSUE TITLE
If a path is long enough, the line is no longer being drawn

### ISSUE THREAD

**Issue by kbdbrnwsk** [x-team/unleash#63]
![screenshot 2015-05-22 17 21 37](https://cloud.githubusercontent.com/assets/7212882/7781628/34318d6a-00a7-11e5-98a7-d2cfc5b7d057.png)

**Comment by szymonmichalak** [comment]
@theanxy please check if this solution works well.
Previously the height of SVG was set to fixed 2000px, so I made it dynamic (by calculating the height of polyline). Width is still fixed to 900px, but please let me know if we should change that as well.

**Comment by kbdbrnwsk** [comment]
Verified.
