### ISSUE TITLE
"Reply to this comment" styling

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#86]
Please use the same styling for all buttons.

http://screencast.com/t/LKgKIkS64

Also please change "send" to "Send".

**Comment by karolsojko** [comment]
@jkbdbrnwsk is this still relevant? The buttons look a bit different: https://www.dropbox.com/s/50rerplt9uk50ey/Screenshot%202016-01-19%2014.23.23.png?dl=0

**Comment by jkbdbrnwsk** [comment]
It's fine on staging, although the "Mark as achieved" is grey now, for some reason. Would be good to make it green again. :)

https://www.dropbox.com/s/5t4xtxeyvjtae1i/Screenshot%202016-01-19%2014.41.55.png?dl=0
