### ISSUE TITLE
Path editor: Add the possibility to place new card between cards already placed in the "drop area"

### ISSUE THREAD

**Issue by kbdbrnwsk** [x-team/unleash#9]
Currently you can drop a new card solely at the end of the row. Would be great to have the possibility of dropping it anywhere you want; cards would re-arrange automatically. I think this is quite necessary due to my premonition that Paths will evolve into more detailed versions with time.

**Comment by theanxy** [comment]
The way the drag&drop interface is currently implemented doesn’t allow for dropping cards into chosen places, but this new box will make it possible to swap the order of cards once they are added.

Success criteria:
- In 'reorder cards' box, use drag&drop interface to swap two given cards,
- Verify that the order of cards has been updated.

@kbdbrnwsk Please verify on http://staging.unleash.x-team.com/.

**Comment by kbdbrnwsk** [comment]
Hey, Wojtek!

Seems it doesn't work properly… Please take a look: http://screencast.com/t/FEVYrIm1RTjH

**Comment by kbdbrnwsk** [comment]
Fixed in the latest commit. Thanks! Closing.
