### ISSUE TITLE
Notifications wording improvements

### ISSUE THREAD

**Issue by jkbdbrnwsk** [x-team/unleash#98]
## E-MAIL + SLACKBOT (COMMENTS NOTIFICATIONS)

*New:*

> Hello, Name Surname!
> 
> Name Surname LEAVE CURRENT WORDING:
> 
> <i>Comment</i>
> 
> Visit the Path to read the full conversation!

### A notification for the Path owner:

Please make sure it’s also sent to the card/path owner via **slackbot** (as comments notifications are).

*Old:*

> Your card: “CARD_NAME” is overdue!

*New:*

> Your “GOAL_NAME” goal is overdue… Feel free to reach out to your Unleasher if you need any help!

or

> Your “GOAL_NAME” goal is due in X days… Feel free to reach out to your Unleasher if you need any help!

### A notification for Unleashers:

> Name Surname's "GOAL_NAME" goal is overdue!

or

> Name Surname's "GOAL_NAME" goal is due in X days!

**Comment by theanxy** [comment]
This has been handled in https://github.com/x-team/unleash-slack-bot/commit/c99dd03e00be28d35d290916bfc048f8a0fe5ec4 and it’s deployed already. Please test :bug:

**Comment by jkbdbrnwsk** [comment]
Hey Fellows, can you please double check those notifications have been updated?

Also looks like the bot is not sending reminders about new card comments, so would appreciate taking another look. Cheers!

cc @Tade0 @theanxy

**Comment by theanxy** [comment]
Wording for email and slack notifications has been updated.

Creating a new issue to address problems with slack private messages.
